# Generated by Django 3.2 on 2022-05-29 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0002_auto_20220528_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookitem',
            name='rent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('263535f9-aaca-4bac-b900-e935634073a0'), editable=False),
        ),
    ]
