# Generated by Django 3.2 on 2022-05-29 06:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20220529_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2487fff7-9681-48cf-8cab-f9395b2f9972'), editable=False),
        ),
    ]
