# Generated by Django 3.2 on 2022-05-29 07:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_bookitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d73dcafe-540f-463e-b21d-a7b5c8d9d583'), editable=False),
        ),
    ]
