# Generated by Django 3.2 on 2022-05-29 09:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_alter_bookitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2f4d53f6-99a7-4428-923f-64e2b1bbb7f6'), editable=False),
        ),
    ]
