# Generated by Django 3.2 on 2022-05-29 09:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_bookitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9ee990ee-1c12-41e3-bd57-6bda35b5a29b'), editable=False),
        ),
    ]
